services:
  bank-import-rogers-bank:
    <<: &bank-import
      build: .
      platform: linux/arm64
      env_file: .env
      restart: "no"
    environment:
      BANK: rogers-bank
      DRY_RUN: "true"
  bank-import-nbdb:
    <<: *bank-import
    environment:
      BANK: nbdb
      DRY_RUN: "true"
