services:
  bank-import-bmo:
    <<: &bank-import
      build:
        context: .
        dockerfile: Dockerfile
      env_file: .env
      restart: no
    environment:
      BANK: bmo

  bank-import-rogers-bank:
    <<: *bank-import
    environment:
      BANK: rogers-bank
